resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: TIME_BASED
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        waitDurationInOpenState: 60s
        failureRateThreshold: 50
        ignoreExceptions:
          - com.czerniecka.order.exceptions.ItemNotAvailable
          - com.czerniecka.order.exceptions.OrderNotFound
          - org.springframework.web.bind.MethodArgumentNotValidException
    instances:
      inventory-service-cb:
        baseConfig: default
      product-service-cb:
        baseConfig: default