resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: TIME_BASED
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        waitDurationInOpenState: 60s
        failureRateThreshold: 50
        ignoreExceptions:
          - org.springframework.web.bind.MethodArgumentNotValidException
          - com.czerniecka.product.exceptions.ProductNotFound
    instances:
      inventory-service-cb:
        baseConfig: default
      supplier-service-cb:
        baseConfig: default