resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: TIME_BASED
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        waitDurationInOpenState: 60s
        failureRateThreshold: 50
        ignoreExceptions:
          - org.springframework.web.bind.MethodArgumentNotValidException
          - com.czerniecka.invoice.exceptions.InvoiceNotFound
      instances:
        product-service-cb:
          baseConfig: default
        inventory-service-cb:
          baseConfig: default

