resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: TIME_BASED
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        waitDurationInOpenState: 60s
        failureRateThreshold: 50
        ignoreExceptions:
          - com.czerniecka.inventory.exceptions.InventoryNotFound
          - org.springframework.web.bind.MethodArgumentNotValidException
    instances:
      product-service-cb:
        baseConfig: default